---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: gradle
    tag: 'latest'

inputs:
  - name: music-repo

outputs:
  - name: build-output

run:
  user: root
  path: music-repo/ci/tasks/build-artifact.sh
