resources:
- name: music-repo
  type: git
  source:
    uri: https://github.com/Erdk/concourse-spring-music
    branch: master

jobs:
- name: unit
  plan:
  - get: music-repo
    trigger: true
  - task: unit
    file: music-repo/ci/tasks/unit.yml

- name: build-binary
  serial: true
  plan:
  - get: music-repo
    passed: [unit]
    trigger: true
  - task: build-artifact
    file: music-repo/ci/tasks/build-artifact.yml
    timeout: 5m
