resources:
- name: music-repo
  type: git
  source:
    uri: git@github.com:Erdk/concourse-spring-music.git
    branch: master
    private_key: ((gh_key)) 
- name: pivotal
  type: cf
  source:
    api: ((cf_api))
    organization: ((cf_org))
    username: ((cf_usr))
    password: ((cf_pass))
    space: ((cf_space))
    skip_cert_check: true

jobs:
- name: unit
  public: true
  plan:
  - get: music-repo
    trigger: true
  - task: unit
    file: music-repo/ci/tasks/unit.yml

- name: build-binary
  serial: true
  public: true
  plan:
  - get: music-repo
    passed: [unit]
    trigger: true
  - task: build-artifact
    file: music-repo/ci/tasks/build-artifact.yml
    timeout: 5m
  - put: pivotal
    params:
      manifest: music-repo/manifest.yml
      file: build-output/spring-music-1.0.war
