resources:
- name: music-repo
  type: git
  source:
    uri: git@github.com:Erdk/concourse-spring-music.git
    branch: master
    private_key: ((gh_key)) 

jobs:
- name: unit
  plan:
  - get: music-repo
    trigger: true
  - task: unit
    file: music-repo/ci/tasks/unit.yml

- name: build-binary
  serial: true
  plan:
  - get: music-repo
    passed: [unit]
    trigger: true
  - task: build-artifact
    file: music-repo/ci/tasks/build-artifact.yml
    timeout: 5m
